name: pdflink
description: "Effortlessly open and view your PDFs directly from the app, utilizing your device's native PDF viewer for a seamless experience."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  open_filex: ^4.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  url_launcher: ^6.0.0
  path_provider: ^2.0.0
  file_picker: '>=8.1.2'
  http: ^1.0.0
  permission_handler: ^12.0.0
  share_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
